CREATE TABLE loan_data (
    id text,
    address_state VARCHAR(10),
    application_type VARCHAR(50),
    emp_length VARCHAR(50),
    emp_title TEXT,
    grade VARCHAR(5),
    home_ownership VARCHAR(20),
    issue_date text,
    last_credit_pull_date text,
    last_payment_date text,
    loan_status VARCHAR(50),
    next_payment_date text,
    member_id BIGINT,
    purpose VARCHAR(100),
    sub_grade VARCHAR(10),
    term VARCHAR(30),
    verification_status VARCHAR(50),
    annual_income NUMERIC,
    dti NUMERIC,
    installment NUMERIC,
    int_rate NUMERIC,
    loan_amount NUMERIC,
    total_acc INTEGER,
    total_payment NUMERIC
);